language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "pypy"
install: "pip install -r requirements.txt"
script: "coverage run -m unittest -v tests"
cache: pip
after_success:
  - codecov